function t389_scrollToTop(){$('html, body').animate({scrollTop:0},700)}
function t396_init(recid){var data='';var res=t396_detectResolution();var ab=$('#rec'+recid).find('.t396__artboard');window.tn_window_width=$(window).width();window.tn_scale_factor=Math.round((window.tn_window_width/res)*100)/100;t396_initTNobj();t396_switchResolution(res);t396_updateTNobj();t396_artboard_build(data,recid);$(window).resize(function(){tn_console('>>>> t396: Window on Resize event >>>>');t396_waitForFinalEvent(function(){if($isMobile){var ww=$(window).width();if(ww!=window.tn_window_width){t396_doResize(recid)}}else{t396_doResize(recid)}},500,'resizeruniqueid'+recid)});$(window).on("orientationchange",function(){tn_console('>>>> t396: Orient change event >>>>');t396_waitForFinalEvent(function(){t396_doResize(recid)},600,'orientationuniqueid'+recid)});$(window).on('load',function(){t396_allelems__renderView(ab);if(typeof t_lazyload_update==='function'&&ab.css('overflow')==='auto'){ab.bind('scroll',t_throttle(function(){if(window.lazy==='y'||$('#allrecords').attr('data-tilda-lazy')==='yes'){t_onFuncLoad('t_lazyload_update',function(){t_lazyload_update()})}},500))}
if(window.location.hash!==''&&ab.css('overflow')==='visible'){ab.css('overflow','hidden');setTimeout(function(){ab.css('overflow','visible')},1)}});var rec=$('#rec'+recid);if(rec.attr('data-connect-with-tab')=='yes'){rec.find('.t396').bind('displayChanged',function(){var ab=rec.find('.t396__artboard');t396_allelems__renderView(ab)})}
if(isSafari)rec.find('.t396').addClass('t396_safari');var isScaled=t396_ab__getFieldValue(ab,'upscale')==='window';var isTildaModeEdit=$('#allrecords').attr('data-tilda-mode')=='edit';if(isScaled&&!isTildaModeEdit)t396_scaleBlock(recid)}
function t396_getRotateValue(matrix){var values=matrix.split('(')[1].split(')')[0].split(',');var a=values[0];var b=values[1];var c=values[2];var d=values[3];var scale=Math.sqrt(a*a+b*b);var sin=b/scale;var angle=Math.round(Math.atan2(b,a)*(180/Math.PI));return angle}
function t396_isOnlyScalableBrowser(){var isFirefox=navigator.userAgent.search("Firefox")!==-1;var isOpera=(!!window.opr&&!!opr.addons)||!!window.opera||navigator.userAgent.indexOf(' OPR/')>=0;return isFirefox||isOpera}
function t396_scaleBlock(recid){var isOnlyScalable=t396_isOnlyScalableBrowser();var res=t396_detectResolution();var rec=$('#rec'+recid);var $ab=rec.find('.t396__artboard');var abWidth=$ab.width();var updatedBlockHeight=Math.floor($ab.height()*window.tn_scale_factor);var ab_height_vh=t396_ab__getFieldValue($ab,'height_vh');window.tn_scale_offset=(abWidth*window.tn_scale_factor-abWidth)/2;if(ab_height_vh!=''){var ab_min_height=t396_ab__getFieldValue($ab,'height');var ab_max_height=t396_ab__getHeight($ab);var scaledMinHeight=ab_min_height*window.tn_scale_factor;updatedBlockHeight=(scaledMinHeight>=ab_max_height)?scaledMinHeight:ab_max_height}
$ab.addClass('t396__artboard_scale');var styleStr='<style class="t396__scale-style">'+'.t-rec#rec'+recid+' { overflow: visible; }'+'#rec'+recid+' .t396__carrier,'+'#rec'+recid+' .t396__filter,'+'#rec'+recid+' .t396__artboard {'+'height: '+updatedBlockHeight+'px !important;'+'width: 100vw !important;'+'max-width: 100%;'+'}'+'<style>';$ab.append(styleStr);rec.find('.t396__elem').each(function(){var $el=$(this);var containerProp=t396_elem__getFieldValue($el,'container');if(containerProp==='grid'){if(isOnlyScalable){var scaleProp='scale('+window.tn_scale_factor+')';$el.find('.tn-atom').wrap("<div class='tn-atom__scale-wrapper' style='transform: scale("+window.tn_scale_factor+"); transform-origin: left top;'></div>")}else{$el.css('zoom',window.tn_scale_factor);if($el.attr('data-elem-type')==='text'&&res<1200)$el.find('.tn-atom').css('-webkit-text-size-adjust','auto');$el.find('.tn-atom').css('transform-origin','center')}}})}
function t396_doResize(recid){var isOnlyScalable=t396_isOnlyScalableBrowser();var ww;var rec=$('#rec'+recid);if($isMobile){ww=$(window).width()}else{ww=window.innerWidth}
var res=t396_detectResolution();rec.find('.t396__scale-style').remove();if(!isOnlyScalable){rec.find('.t396__elem').css('zoom','');rec.find('.t396__elem .tn-atom').css('transform-origin','')}else{rec.find('.tn-atom').unwrap('.tn-atom__scale-wrapper')}
var ab=rec.find('.t396__artboard');var abWidth=ab.width();window.tn_window_width=ww;window.tn_scale_factor=Math.round((window.tn_window_width/res)*100)/100;window.tn_scale_offset=(abWidth*window.tn_scale_factor-abWidth)/2;t396_switchResolution(res);t396_updateTNobj();t396_ab__renderView(ab);t396_allelems__renderView(ab);var isTildaModeEdit=$('#allrecords').attr('data-tilda-mode')=='edit';var isScaled=t396_ab__getFieldValue(ab,'upscale')==='window';if(isScaled&&!isTildaModeEdit)t396_scaleBlock(recid)}
function t396_detectResolution(){var ww;if($isMobile){ww=$(window).width()}else{ww=window.innerWidth}
var res;res=1200;if(ww<1200){res=960}
if(ww<960){res=640}
if(ww<640){res=480}
if(ww<480){res=320}
return(res)}
function t396_initTNobj(){tn_console('func: initTNobj');window.tn={};window.tn.canvas_min_sizes=["320","480","640","960","1200"];window.tn.canvas_max_sizes=["480","640","960","1200",""];window.tn.ab_fields=["height","width","bgcolor","bgimg","bgattachment","bgposition","filteropacity","filtercolor","filteropacity2","filtercolor2","height_vh","valign"]}
function t396_updateTNobj(){tn_console('func: updateTNobj');if(typeof window.zero_window_width_hook!='undefined'&&window.zero_window_width_hook=='allrecords'&&$('#allrecords').length){window.tn.window_width=parseInt($('#allrecords').width())}else{window.tn.window_width=parseInt($(window).width())}
if($isMobile){window.tn.window_height=parseInt($(window).height())}else{window.tn.window_height=parseInt(window.innerHeight)}
if(window.tn.curResolution==1200){window.tn.canvas_min_width=1200;window.tn.canvas_max_width=window.tn.window_width}
if(window.tn.curResolution==960){window.tn.canvas_min_width=960;window.tn.canvas_max_width=1200}
if(window.tn.curResolution==640){window.tn.canvas_min_width=640;window.tn.canvas_max_width=960}
if(window.tn.curResolution==480){window.tn.canvas_min_width=480;window.tn.canvas_max_width=640}
if(window.tn.curResolution==320){window.tn.canvas_min_width=320;window.tn.canvas_max_width=480}
window.tn.grid_width=window.tn.canvas_min_width;window.tn.grid_offset_left=parseFloat((window.tn.window_width-window.tn.grid_width)/2)}
var t396_waitForFinalEvent=(function(){var timers={};return function(callback,ms,uniqueId){if(!uniqueId){uniqueId="Don't call this twice without a uniqueId"}
if(timers[uniqueId]){clearTimeout(timers[uniqueId])}
timers[uniqueId]=setTimeout(callback,ms)}})();function t396_switchResolution(res,resmax){tn_console('func: switchResolution');if(typeof resmax=='undefined'){if(res==1200)resmax='';if(res==960)resmax=1200;if(res==640)resmax=960;if(res==480)resmax=640;if(res==320)resmax=480}
window.tn.curResolution=res;window.tn.curResolution_max=resmax}
function t396_artboard_build(data,recid){tn_console('func: t396_artboard_build. Recid:'+recid);tn_console(data);var ab=$('#rec'+recid).find('.t396__artboard');t396_ab__renderView(ab);ab.find('.tn-elem').each(function(){var item=$(this);if(item.attr('data-elem-type')=='text'){t396_addText(ab,item)}
if(item.attr('data-elem-type')=='image'){t396_addImage(ab,item)}
if(item.attr('data-elem-type')=='shape'){t396_addShape(ab,item)}
if(item.attr('data-elem-type')=='button'){t396_addButton(ab,item)}
if(item.attr('data-elem-type')=='video'){t396_addVideo(ab,item)}
if(item.attr('data-elem-type')=='html'){t396_addHtml(ab,item)}
if(item.attr('data-elem-type')=='tooltip'){t396_addTooltip(ab,item)}
if(item.attr('data-elem-type')=='form'){t396_addForm(ab,item)}
if(item.attr('data-elem-type')=='gallery'){t396_addGallery(ab,item)}});$('#rec'+recid).find('.t396__artboard').removeClass('rendering').addClass('rendered');if(ab.attr('data-artboard-ovrflw')=='visible'){$('#allrecords').css('overflow','hidden')}
if($isMobile){$('#rec'+recid).append('<style>@media only screen and (min-width:1366px) and (orientation:landscape) and (-webkit-min-device-pixel-ratio:2) {.t396__carrier {background-attachment:scroll!important;}}</style>')}}
function t396_ab__renderView(ab){var fields=window.tn.ab_fields;for(var i=0;i<fields.length;i++){t396_ab__renderViewOneField(ab,fields[i])}
var ab_min_height=t396_ab__getFieldValue(ab,'height');var ab_max_height=t396_ab__getHeight(ab);var isTildaModeEdit=$('#allrecords').attr('data-tilda-mode')=='edit';var isScaled=t396_ab__getFieldValue(ab,'upscale')==='window';var ab_height_vh=t396_ab__getFieldValue(ab,'height_vh');if(isScaled&&!isTildaModeEdit&&ab_height_vh!='')var scaledMinHeight=parseInt(ab_min_height,10)*window.tn_scale_factor;var offset_top=0;if(ab_min_height==ab_max_height||(scaledMinHeight&&scaledMinHeight>=ab_max_height)){offset_top=0}else{var ab_valign=t396_ab__getFieldValue(ab,'valign');if(ab_valign=='top'){offset_top=0}else if(ab_valign=='center'){if(scaledMinHeight){offset_top=parseFloat((ab_max_height-scaledMinHeight)/2).toFixed(1)}else{offset_top=parseFloat((ab_max_height-ab_min_height)/2).toFixed(1)}}else if(ab_valign=='bottom'){if(scaledMinHeight){offset_top=parseFloat((ab_max_height-scaledMinHeight)).toFixed(1)}else{offset_top=parseFloat((ab_max_height-ab_min_height)).toFixed(1)}}else if(ab_valign=='stretch'){offset_top=0;ab_min_height=ab_max_height}else{offset_top=0}}
ab.attr('data-artboard-proxy-min-offset-top',offset_top);ab.attr('data-artboard-proxy-min-height',ab_min_height);ab.attr('data-artboard-proxy-max-height',ab_max_height);var filter=ab.find('.t396__filter');var carrier=ab.find('.t396__carrier');var abHeightVh=t396_ab__getFieldValue(ab,'height_vh');abHeightVh=parseFloat(abHeightVh);if(window.isMobile&&abHeightVh){var height=document.documentElement.clientHeight*parseFloat(abHeightVh/100);ab.css('height',height);filter.css('height',height);carrier.css('height',height)}}
function t396_addText(ab,el){tn_console('func: addText');var fields_str='top,left,width,container,axisx,axisy,widthunits,leftunits,topunits';var fields=fields_str.split(',');el.attr('data-fields',fields_str);t396_elem__renderView(el)}
function t396_addImage(ab,el){tn_console('func: addImage');var fields_str='img,width,filewidth,fileheight,top,left,container,axisx,axisy,widthunits,leftunits,topunits';var fields=fields_str.split(',');el.attr('data-fields',fields_str);t396_elem__renderView(el);el.find('img').on("load",function(){t396_elem__renderViewOneField(el,'top');if(typeof $(this).attr('src')!='undefined'&&$(this).attr('src')!=''){setTimeout(function(){t396_elem__renderViewOneField(el,'top')},2000)}}).each(function(){if(this.complete)$(this).trigger('load')});el.find('img').on('tuwidget_done',function(e,file){t396_elem__renderViewOneField(el,'top')})}
function t396_addShape(ab,el){tn_console('func: addShape');var fields_str='width,height,top,left,';fields_str+='container,axisx,axisy,widthunits,heightunits,leftunits,topunits';var fields=fields_str.split(',');el.attr('data-fields',fields_str);t396_elem__renderView(el)}
function t396_addButton(ab,el){tn_console('func: addButton');var fields_str='top,left,width,height,container,axisx,axisy,caption,leftunits,topunits';var fields=fields_str.split(',');el.attr('data-fields',fields_str);t396_elem__renderView(el);return(el)}
function t396_addVideo(ab,el){tn_console('func: addVideo');var fields_str='width,height,top,left,';fields_str+='container,axisx,axisy,widthunits,heightunits,leftunits,topunits';var fields=fields_str.split(',');el.attr('data-fields',fields_str);t396_elem__renderView(el);var viel=el.find('.tn-atom__videoiframe');var viatel=el.find('.tn-atom');viatel.css('background-color','#000');var vihascover=viatel.attr('data-atom-video-has-cover');if(typeof vihascover=='undefined'){vihascover=''}
if(vihascover=='y'){viatel.click(function(){var viifel=viel.find('iframe');if(viifel.length){var foo=viifel.attr('data-original');viifel.attr('src',foo)}
viatel.css('background-image','none');viatel.find('.tn-atom__video-play-link').css('display','none')})}
var autoplay=t396_elem__getFieldValue(el,'autoplay');var showinfo=t396_elem__getFieldValue(el,'showinfo');var loop=t396_elem__getFieldValue(el,'loop');var mute=t396_elem__getFieldValue(el,'mute');var startsec=t396_elem__getFieldValue(el,'startsec');var endsec=t396_elem__getFieldValue(el,'endsec');var tmode=$('#allrecords').attr('data-tilda-mode');var url='';var viyid=viel.attr('data-youtubeid');if(typeof viyid!='undefined'&&viyid!=''){url='//youtube.com/embed/';url+=viyid+'?rel=0&fmt=18&html5=1';url+='&showinfo='+(showinfo=='y'?'1':'0');if(loop=='y'){url+='&loop=1&playlist='+viyid}
if(startsec>0){url+='&start='+startsec}
if(endsec>0){url+='&end='+endsec}
if(mute=='y'){url+='&mute=1'}
if(vihascover=='y'){url+='&autoplay=1';var instFlag='y';var iframeClass='';if(autoplay=='y'&&mute=='y'&&window.lazy=='y'){instFlag='lazy';iframeClass=' class="t-iframe"'}
viel.html('<iframe id="youtubeiframe"'+iframeClass+' width="100%" height="100%" data-original="'+url+'" frameborder="0" allowfullscreen data-flag-inst="'+instFlag+'"></iframe>');if(autoplay=='y'&&mute=='y'&&window.lazy=='y'){el.append('<script>lazyload_iframe = new LazyLoad({elements_selector: ".t-iframe"});<\/script>')}
if(autoplay=='y'&&mute=='y'){viatel.trigger('click')}}else{if(typeof tmode!='undefined'&&tmode=='edit'){}else{if(autoplay=='y'){url+='&autoplay=1'}}
if(window.lazy=='y'){viel.html('<iframe id="youtubeiframe" class="t-iframe" width="100%" height="100%" data-original="'+url+'" frameborder="0" allowfullscreen data-flag-inst="lazy"></iframe>');el.append('<script>lazyload_iframe = new LazyLoad({elements_selector: ".t-iframe"});<\/script>')}else{viel.html('<iframe id="youtubeiframe" width="100%" height="100%" src="'+url+'" frameborder="0" allowfullscreen data-flag-inst="y"></iframe>')}}}
var vivid=viel.attr('data-vimeoid');if(typeof vivid!='undefined'&&vivid>0){url='//player.vimeo.com/video/';url+=vivid+'?color=ffffff&badge=0';if(showinfo=='y'){url+='&title=1&byline=1&portrait=1'}else{url+='&title=0&byline=0&portrait=0'}
if(loop=='y'){url+='&loop=1'}
if(mute=='y'){url+='&muted=1'}
if(vihascover=='y'){url+='&autoplay=1';viel.html('<iframe data-original="'+url+'" width="100%" height="100%" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>')}else{if(typeof tmode!='undefined'&&tmode=='edit'){}else{if(autoplay=='y'){url+='&autoplay=1'}}
if(window.lazy=='y'){viel.html('<iframe class="t-iframe" data-original="'+url+'" width="100%" height="100%" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>');el.append('<script>lazyload_iframe = new LazyLoad({elements_selector: ".t-iframe"});<\/script>')}else{viel.html('<iframe src="'+url+'" width="100%" height="100%" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>')}}}}
function t396_addHtml(ab,el){tn_console('func: addHtml');var fields_str='width,height,top,left,';fields_str+='container,axisx,axisy,widthunits,heightunits,leftunits,topunits';var fields=fields_str.split(',');el.attr('data-fields',fields_str);t396_elem__renderView(el)}
function t396_addTooltip(ab,el){tn_console('func: addTooltip');var fields_str='width,height,top,left,';fields_str+='container,axisx,axisy,widthunits,heightunits,leftunits,topunits,tipposition';var fields=fields_str.split(',');el.attr('data-fields',fields_str);t396_elem__renderView(el);var pinEl=el.find('.tn-atom__pin');var tipEl=el.find('.tn-atom__tip');var tipopen=el.attr('data-field-tipopen-value');if(isMobile||(typeof tipopen!='undefined'&&tipopen=='click')){t396_setUpTooltip_mobile(el,pinEl,tipEl)}else{t396_setUpTooltip_desktop(el,pinEl,tipEl)}
setTimeout(function(){$('.tn-atom__tip-img').each(function(){var foo=$(this).attr('data-tipimg-original');if(typeof foo!='undefined'&&foo!=''){$(this).attr('src',foo)}})},3000)}
function t396_addForm(ab,el){tn_console('func: addForm');var fields_str='width,top,left,';fields_str+='inputs,container,axisx,axisy,widthunits,leftunits,topunits';var fields=fields_str.split(',');el.attr('data-fields',fields_str);t396_elem__renderView(el)}
function t396_addGallery(ab,el){tn_console('func: addForm');var fields_str='width,height,top,left,';fields_str+='imgs,container,axisx,axisy,widthunits,heightunits,leftunits,topunits';var fields=fields_str.split(',');el.attr('data-fields',fields_str);t396_elem__renderView(el)}
function t396_elem__setFieldValue(el,prop,val,flag_render,flag_updateui,res){if(res=='')res=window.tn.curResolution;if(res<1200&&prop!='zindex'){el.attr('data-field-'+prop+'-res-'+res+'-value',val)}else{el.attr('data-field-'+prop+'-value',val)}
if(flag_render=='render')elem__renderViewOneField(el,prop);if(flag_updateui=='updateui')panelSettings__updateUi(el,prop,val)}
function t396_elem__getFieldValue(el,prop){var res=window.tn.curResolution;var r;if(res<1200){if(res==960){r=el.attr('data-field-'+prop+'-res-960-value');if(typeof r=='undefined'){r=el.attr('data-field-'+prop+'-value')}}
if(res==640){r=el.attr('data-field-'+prop+'-res-640-value');if(typeof r=='undefined'){r=el.attr('data-field-'+prop+'-res-960-value');if(typeof r=='undefined'){r=el.attr('data-field-'+prop+'-value')}}}
if(res==480){r=el.attr('data-field-'+prop+'-res-480-value');if(typeof r=='undefined'){r=el.attr('data-field-'+prop+'-res-640-value');if(typeof r=='undefined'){r=el.attr('data-field-'+prop+'-res-960-value');if(typeof r=='undefined'){r=el.attr('data-field-'+prop+'-value')}}}}
if(res==320){r=el.attr('data-field-'+prop+'-res-320-value');if(typeof r=='undefined'){r=el.attr('data-field-'+prop+'-res-480-value');if(typeof r=='undefined'){r=el.attr('data-field-'+prop+'-res-640-value');if(typeof r=='undefined'){r=el.attr('data-field-'+prop+'-res-960-value');if(typeof r=='undefined'){r=el.attr('data-field-'+prop+'-value')}}}}}}else{r=el.attr('data-field-'+prop+'-value')}
return(r)}
function t396_elem__renderView(el){tn_console('func: elem__renderView');var fields=el.attr('data-fields');if(!fields){return!1}
fields=fields.split(',');for(var i=0;i<fields.length;i++){t396_elem__renderViewOneField(el,fields[i])}}
function t396_elem__renderViewOneField(el,field){var value=t396_elem__getFieldValue(el,field);if(field=='left'){value=t396_elem__convertPosition__Local__toAbsolute(el,field,value);el.css('left',parseFloat(value).toFixed(1)+'px')}
if(field=='top'){var ab=el.parents('.t396__artboard');value=t396_elem__convertPosition__Local__toAbsolute(el,field,value);el.css('top',parseFloat(value).toFixed(1)+'px')}
if(field=='width'){value=t396_elem__getWidth(el,value);el.css('width',parseFloat(value).toFixed(1)+'px');var eltype=el.attr('data-elem-type');if(eltype=='tooltip'){var pinSvgIcon=el.find('.tn-atom__pin-icon');if(pinSvgIcon.length>0){var pinSize=parseFloat(value).toFixed(1)+'px';pinSvgIcon.css({'width':pinSize,'height':pinSize})}
el.css('height',parseInt(value).toFixed(1)+'px')}
if(eltype=='gallery'){var borderWidth=t396_elem__getFieldValue(el,'borderwidth');var borderStyle=t396_elem__getFieldValue(el,'borderstyle');if(borderStyle=='none'||typeof borderStyle=='undefined'||typeof borderWidth=='undefined'||borderWidth=='')borderWidth=0;value=value*1-borderWidth*2;el.css('width',parseFloat(value).toFixed(1)+'px');el.find('.t-slds__main').css('width',parseFloat(value).toFixed(1)+'px');el.find('.tn-atom__slds-img').css('width',parseFloat(value).toFixed(1)+'px')}}
if(field=='height'){var eltype=el.attr('data-elem-type');if(eltype=='tooltip'){return}
value=t396_elem__getHeight(el,value);el.css('height',parseFloat(value).toFixed(1)+'px');if(eltype==='gallery'){var borderWidth=t396_elem__getFieldValue(el,'borderwidth');var borderStyle=t396_elem__getFieldValue(el,'borderstyle');if(borderStyle=='none'||typeof borderStyle=='undefined'||typeof borderWidth=='undefined'||borderWidth=='')borderWidth=0;value=value*1-borderWidth*2;el.css('height',parseFloat(value).toFixed(1)+'px');el.find('.tn-atom__slds-img').css('height',parseFloat(value).toFixed(1)+'px');el.find('.t-slds__main').css('height',parseFloat(value).toFixed(1)+'px')}}
if(field=='container'){t396_elem__renderViewOneField(el,'left');t396_elem__renderViewOneField(el,'top')}
if(field=='width'||field=='height'||field=='fontsize'||field=='fontfamily'||field=='letterspacing'||field=='fontweight'||field=='img'){t396_elem__renderViewOneField(el,'left');t396_elem__renderViewOneField(el,'top')}
if(field=='inputs'){value=el.find('.tn-atom__inputs-textarea').val();try{t_zeroForms__renderForm(el,value)}catch(err){}}}
function t396_elem__convertPosition__Local__toAbsolute(el,field,value){var ab=el.parents('.t396__artboard');var blockVAlign=t396_ab__getFieldValue(ab,'valign');var isScaled=t396_ab__getFieldValue(ab,'upscale')==='window';var isTildaModeEdit=$('#allrecords').attr('data-tilda-mode')=='edit';var isOnlyScalable=t396_isOnlyScalableBrowser();var isScaledElement=!isTildaModeEdit&&isScaled&&isOnlyScalable;var isZoomedElement=!isTildaModeEdit&&isScaled&&!isOnlyScalable;var el_axisy=t396_elem__getFieldValue(el,'axisy');value=parseInt(value);if(field=='left'){var el_container,offset_left,el_container_width,el_width;var container=t396_elem__getFieldValue(el,'container');if(container==='grid'){el_container='grid';offset_left=window.tn.grid_offset_left;el_container_width=window.tn.grid_width}else{el_container='window';offset_left=0;el_container_width=window.tn.window_width}
var el_leftunits=t396_elem__getFieldValue(el,'leftunits');if(el_leftunits==='%'){value=t396_roundFloat(el_container_width*value/100)}
if(!isTildaModeEdit&&isScaled){if(container==='grid'&&isOnlyScalable)value=value*window.tn_scale_factor}else{value=offset_left+value}
var el_axisx=t396_elem__getFieldValue(el,'axisx');if(el_axisx==='center'){el_width=t396_elem__getWidth(el);if(isScaledElement&&el_container!=='window'){el_container_width*=window.tn_scale_factor;el_width*=window.tn_scale_factor}
value=el_container_width/2-el_width/2+value}
if(el_axisx==='right'){el_width=t396_elem__getWidth(el);if(isScaledElement&&el_container!=='window'){el_container_width*=window.tn_scale_factor;el_width*=window.tn_scale_factor}
value=el_container_width-el_width+value}}
if(field==='top'){var el_container,offset_top,el_container_height,el_height;var ab=el.parent();var container=t396_elem__getFieldValue(el,'container');if(container==='grid'){el_container='grid';offset_top=parseFloat(ab.attr('data-artboard-proxy-min-offset-top'));el_container_height=parseFloat(ab.attr('data-artboard-proxy-min-height'))}else{el_container='window';offset_top=0;el_container_height=parseFloat(ab.attr('data-artboard-proxy-max-height'))}
var el_topunits=t396_elem__getFieldValue(el,'topunits');if(el_topunits==='%'){value=(el_container_height*(value/100))}
if(isScaledElement&&el_container!=='window'){value*=window.tn_scale_factor}
if(isZoomedElement&&el_container!=='window'){offset_top=blockVAlign==='stretch'?0:(offset_top/window.tn_scale_factor)}
value=offset_top+value;var ab_height_vh=t396_ab__getFieldValue(ab,'height_vh');var ab_min_height=t396_ab__getFieldValue(ab,'height');var ab_max_height=t396_ab__getHeight(ab);if(isScaled&&!isTildaModeEdit&&ab_height_vh!=''){var scaledMinHeight=parseInt(ab_min_height,10)*window.tn_scale_factor}
if(el_axisy==='center'){el_height=t396_elem__getHeight(el);if(el.attr('data-elem-type')==='image'){el_width=t396_elem__getWidth(el);var fileWidth=t396_elem__getFieldValue(el,'filewidth');var fileHeight=t396_elem__getFieldValue(el,'fileheight');if(fileWidth&&fileHeight){var ratio=parseInt(fileWidth)/parseInt(fileHeight);el_height=el_width/ratio}}
if(isScaledElement&&el_container!=='window'){if(blockVAlign!=='stretch'){el_container_height=el_container_height*window.tn_scale_factor}else{if(scaledMinHeight){el_container_height=scaledMinHeight>ab_max_height?scaledMinHeight:ab_max_height}else{el_container_height=ab.height()}}
el_height*=window.tn_scale_factor}
if(!isTildaModeEdit&&isScaled&&!isOnlyScalable&&el_container!=='window'&&blockVAlign==='stretch'){if(scaledMinHeight){el_container_height=scaledMinHeight>ab_max_height?scaledMinHeight:ab_max_height}else{el_container_height=ab.height()}
el_container_height=el_container_height/window.tn_scale_factor}
value=el_container_height/2-el_height/2+value}
if(el_axisy==='bottom'){el_height=t396_elem__getHeight(el);if(el.attr('data-elem-type')==='image'){el_width=t396_elem__getWidth(el);var fileWidth=t396_elem__getFieldValue(el,'filewidth');var fileHeight=t396_elem__getFieldValue(el,'fileheight');if(fileWidth&&fileHeight){var ratio=parseInt(fileWidth)/parseInt(fileHeight);el_height=el_width/ratio}}
if(isScaledElement&&el_container!=='window'){if(blockVAlign!=='stretch'){el_container_height=el_container_height*window.tn_scale_factor}else{if(scaledMinHeight){el_container_height=scaledMinHeight>ab_max_height?scaledMinHeight:ab_max_height}else{el_container_height=ab.height()}}
el_height*=window.tn_scale_factor}
if(!isTildaModeEdit&&isScaled&&!isOnlyScalable&&el_container!=='window'&&blockVAlign==='stretch'){if(scaledMinHeight){el_container_height=scaledMinHeight>ab_max_height?scaledMinHeight:ab_max_height}else{el_container_height=ab.height()}
el_container_height=el_container_height/window.tn_scale_factor}
value=el_container_height-el_height+value}}
return(value)}
function t396_ab__setFieldValue(ab,prop,val,res){if(res=='')res=window.tn.curResolution;if(res<1200){ab.attr('data-artboard-'+prop+'-res-'+res,val)}else{ab.attr('data-artboard-'+prop,val)}}
function t396_ab__getFieldValue(ab,prop){var res=window.tn.curResolution;var r;if(res<1200){if(res==960){r=ab.attr('data-artboard-'+prop+'-res-960');if(typeof r=='undefined'){r=ab.attr('data-artboard-'+prop+'')}}
if(res==640){r=ab.attr('data-artboard-'+prop+'-res-640');if(typeof r=='undefined'){r=ab.attr('data-artboard-'+prop+'-res-960');if(typeof r=='undefined'){r=ab.attr('data-artboard-'+prop+'')}}}
if(res==480){r=ab.attr('data-artboard-'+prop+'-res-480');if(typeof r=='undefined'){r=ab.attr('data-artboard-'+prop+'-res-640');if(typeof r=='undefined'){r=ab.attr('data-artboard-'+prop+'-res-960');if(typeof r=='undefined'){r=ab.attr('data-artboard-'+prop+'')}}}}
if(res==320){r=ab.attr('data-artboard-'+prop+'-res-320');if(typeof r=='undefined'){r=ab.attr('data-artboard-'+prop+'-res-480');if(typeof r=='undefined'){r=ab.attr('data-artboard-'+prop+'-res-640');if(typeof r=='undefined'){r=ab.attr('data-artboard-'+prop+'-res-960');if(typeof r=='undefined'){r=ab.attr('data-artboard-'+prop+'')}}}}}}else{r=ab.attr('data-artboard-'+prop)}
return(r)}
function t396_ab__renderViewOneField(ab,field){var value=t396_ab__getFieldValue(ab,field)}
function t396_allelems__renderView(ab){tn_console('func: allelems__renderView: abid:'+ab.attr('data-artboard-recid'));ab.find(".tn-elem").each(function(){t396_elem__renderView($(this))})}
function t396_ab__filterUpdate(ab){var filter=ab.find('.t396__filter');var c1=filter.attr('data-filtercolor-rgb');var c2=filter.attr('data-filtercolor2-rgb');var o1=filter.attr('data-filteropacity');var o2=filter.attr('data-filteropacity2');if((typeof c2=='undefined'||c2=='')&&(typeof c1!='undefined'&&c1!='')){filter.css("background-color","rgba("+c1+","+o1+")")}else if((typeof c1=='undefined'||c1=='')&&(typeof c2!='undefined'&&c2!='')){filter.css("background-color","rgba("+c2+","+o2+")")}else if(typeof c1!='undefined'&&typeof c2!='undefined'&&c1!=''&&c2!=''){filter.css({background:"-webkit-gradient(linear, left top, left bottom, from(rgba("+c1+","+o1+")), to(rgba("+c2+","+o2+")) )"})}else{filter.css("background-color",'transparent')}}
function t396_ab__getHeight(ab,ab_height){if(typeof ab_height=='undefined')ab_height=t396_ab__getFieldValue(ab,'height');ab_height=parseFloat(ab_height);var ab_height_vh=t396_ab__getFieldValue(ab,'height_vh');if(ab_height_vh!=''){ab_height_vh=parseFloat(ab_height_vh);if(isNaN(ab_height_vh)===!1){var ab_height_vh_px=parseFloat(window.tn.window_height*parseFloat(ab_height_vh/100));if(ab_height<ab_height_vh_px){ab_height=ab_height_vh_px}}}
return(ab_height)}
function t396_hex2rgb(hexStr){var hex=parseInt(hexStr.substring(1),16);var r=(hex&0xff0000)>>16;var g=(hex&0x00ff00)>>8;var b=hex&0x0000ff;return[r,g,b]}
String.prototype.t396_replaceAll=function(search,replacement){var target=this;return target.replace(new RegExp(search,'g'),replacement)};function t396_elem__getWidth(el,value){if(typeof value=='undefined')value=parseFloat(t396_elem__getFieldValue(el,'width'));var el_widthunits=t396_elem__getFieldValue(el,'widthunits');if(el_widthunits=='%'){var el_container=t396_elem__getFieldValue(el,'container');if(el_container=='window'){value=parseFloat(window.tn.window_width*parseFloat(parseInt(value)/100))}else{value=parseFloat(window.tn.grid_width*parseFloat(parseInt(value)/100))}}
return(value)}
function t396_elem__getHeight(el,value){if(typeof value=='undefined')value=t396_elem__getFieldValue(el,'height');value=parseFloat(value);if(el.attr('data-elem-type')=='shape'||el.attr('data-elem-type')=='video'||el.attr('data-elem-type')=='html'||el.attr('data-elem-type')=='gallery'){var el_heightunits=t396_elem__getFieldValue(el,'heightunits');if(el_heightunits=='%'){var ab=el.parent();var ab_min_height=parseFloat(ab.attr('data-artboard-proxy-min-height'));var ab_max_height=parseFloat(ab.attr('data-artboard-proxy-max-height'));var el_container=t396_elem__getFieldValue(el,'container');if(el_container=='window'){value=parseFloat(ab_max_height*parseFloat(value/100))}else{value=parseFloat(ab_min_height*parseFloat(value/100))}}}else if(el.attr('data-elem-type')=='button'){value=value}else{value=parseFloat(el.innerHeight())}
return(value)}
function t396_roundFloat(n){n=Math.round(n*100)/100;return(n)}
function tn_console(str){if(window.tn_comments==1)console.log(str)}
function t396_setUpTooltip_desktop(el,pinEl,tipEl){var timer;pinEl.mouseover(function(){$('.tn-atom__tip_visible').each(function(){var thisTipEl=$(this).parents('.t396__elem');if(thisTipEl.attr('data-elem-id')!=el.attr('data-elem-id')){t396_hideTooltip(thisTipEl,$(this))}});clearTimeout(timer);if(tipEl.css('display')=='block'){return}
t396_showTooltip(el,tipEl)});pinEl.mouseout(function(){timer=setTimeout(function(){t396_hideTooltip(el,tipEl)},300)})}
function t396_setUpTooltip_mobile(el,pinEl,tipEl){pinEl.on('click',function(e){if(tipEl.css('display')=='block'&&$(e.target).hasClass("tn-atom__pin")){t396_hideTooltip(el,tipEl)}else{t396_showTooltip(el,tipEl)}});var id=el.attr("data-elem-id");$(document).click(function(e){var isInsideTooltip=($(e.target).hasClass("tn-atom__pin")||$(e.target).parents(".tn-atom__pin").length>0);if(isInsideTooltip){var clickedPinId=$(e.target).parents(".t396__elem").attr("data-elem-id");if(clickedPinId==id){return}}
t396_hideTooltip(el,tipEl)})}
function t396_hideTooltip(el,tipEl){tipEl.css('display','');tipEl.css({"left":"","transform":"","right":""});tipEl.removeClass('tn-atom__tip_visible');el.css('z-index','')}
function t396_showTooltip(el,tipEl){var pos=el.attr("data-field-tipposition-value");if(typeof pos=='undefined'||pos==''){pos='top'};var elSize=el.height();var elTop=el.offset().top;var elBottom=elTop+elSize;var elLeft=el.offset().left;var elRight=el.offset().left+elSize;var winTop=$(window).scrollTop();var winWidth=$(window).width();var winBottom=winTop+$(window).height();var tipElHeight=tipEl.outerHeight();var tipElWidth=tipEl.outerWidth();var padd=15;if(pos=='right'||pos=='left'){var tipElRight=elRight+padd+tipElWidth;var tipElLeft=elLeft-padd-tipElWidth;if((pos=='right'&&tipElRight>winWidth)||(pos=='left'&&tipElLeft<0)){pos='top'}}
if(pos=='top'||pos=='bottom'){var tipElRight=elRight+(tipElWidth/2-elSize/2);var tipElLeft=elLeft-(tipElWidth/2-elSize/2);if(tipElRight>winWidth){var rightOffset=-(winWidth-elRight-padd);tipEl.css({"left":"auto","transform":"none","right":rightOffset+"px"})}
if(tipElLeft<0){var leftOffset=-(elLeft-padd);tipEl.css({"left":leftOffset+"px","transform":"none"})}}
if(pos=='top'){var tipElTop=elTop-padd-tipElHeight;var tipElBottom=elBottom+padd+tipElHeight;if(winBottom>tipElBottom&&winTop>tipElTop){pos='bottom'}}
if(pos=='bottom'){var tipElTop=elTop-padd-tipElHeight;var tipElBottom=elBottom+padd+tipElHeight;if(winBottom<tipElBottom&&winTop<tipElTop){pos='top'}}
tipEl.attr('data-tip-pos',pos);tipEl.css('display','block');tipEl.addClass('tn-atom__tip_visible');el.css('z-index','1000')}
function t396_hex2rgba(hexStr,opacity){var hex=parseInt(hexStr.substring(1),16);var r=(hex&0xff0000)>>16;var g=(hex&0x00ff00)>>8;var b=hex&0x0000ff;return[r,g,b,parseFloat(opacity)]}
function t452_scrollToTop(){$('html, body').animate({scrollTop:0},700)}
function t557_init(recid,snowtype){$('<img/>').attr('src','https://static.tildacdn.com/img/snowflakes_1.png').load(function(){$(this).remove()});$('<img/>').attr('src','https://static.tildacdn.com/img/snowflakes_2.png').load(function(){$(this).remove()});$('<img/>').attr('src','https://static.tildacdn.com/img/snowflakes_3.png').load(function(){$(this).remove();t557__addSnow(recid,snowtype)})}
function t557__addSnow(recid,snowtype){var el=$('#rec'+recid),t557_ids=el.find('.t557__snow-recid-holder').attr('data-snow-rec-ids').split(',');if(t557_ids!=""){t557_ids.forEach(function(rec_id,i,arr){var t557_zeroattr=$('#rec'+rec_id).attr('data-record-type');if(t557_zeroattr==396){var t557_wrappertype=" .t396__artboard"}else{var t557_wrappertype=" .t-cover"}
var t557_cover=document.querySelector('#rec'+rec_id+t557_wrappertype);$(t557_cover).find('.t796__shape-border').css('z-index',1);if(t557_cover!=null){var t557_snow=document.createElement('div');t557_snow.className=snowtype;t557_cover.appendChild(t557_snow)}})}else{t557_cover=$('.t-cover').first();var t557_snow=document.createElement('div');t557_snow.className=snowtype;t557_cover.append(t557_snow)}
$('.'+snowtype).animate({"opacity":"1"},1000,function(){})}
function t806__init(recid){t_onFuncLoad('tvote__init',function(){tvote__init(recid)});var testWrap=$('#rec'+recid);var testContainer=testWrap.find('.t806');var rightAnswersCount;var testAnswers=testWrap.find('.t806__answers');var testBlock=testWrap.find('.t806__test');var testResultWrap=testWrap.find('.t806__result-wrap');var shareVK=testWrap.find('.t806__social-btn-vk');var shareFB=testWrap.find('.t806__social-btn-fb');var shareTwitter=testWrap.find('.t806__social-btn-twitter');var rightTestAnswers=[];var testImgSrc=[];var startTitle=testWrap.find('.t806__start-title').text();var startText=testWrap.find('.t806__start-text').text();var siteLocation=window.location.href;testBlock.addClass('t806__counter');testBlock.attr('data-count',0);testResultWrap.each(function(i){if($(testResultWrap[i]).find('img').attr('src')!==''){testImgSrc.push($(testResultWrap[i]).find('img').attr('src'))}});if(testImgSrc.length==1){testResultWrap.each(function(i){$(testResultWrap[i]).find('img').attr('src',testImgSrc[0]);$(testResultWrap[i]).find('.t806__result-desc').removeClass('t806__result-desc_withoutimg');$(testResultWrap[i]).find('.t806__result-count, .t806__result-variant').css('color','#ffffff')})}
testAnswers.each(function(){var answer=$(this).attr('data-right-answer')||'';rightTestAnswers.push(answer.trim());$(this).removeAttr('data-right-answer')});t806__changeRadio(recid,rightTestAnswers);t806__changeTestInput(recid);t806__startClickBtn(recid);t806__checkClickBtn(recid,rightTestAnswers);t806__nextClickBtn(recid);t806__resultClickBtn(recid);t806__restartClickBtn(recid,rightTestAnswers);shareVK.click(function(){t806_shareVK(recid,startTitle,siteLocation)});shareFB.click(function(){t806_shareFB(recid,startTitle,startText,siteLocation)});shareTwitter.click(function(){t806_shareTwitter(recid,startTitle,siteLocation)});t806__clearFormOnBackClick(testWrap)}
function t806_scrollToTop(testBlock){var topCoordinate=testBlock.offset().top;$('html, body').animate({scrollTop:topCoordinate},0)}
function t806__clearFormOnBackClick(testWrap){window.addEventListener('pagehide',function(){testWrap.find('.t806__input').prop('checked',!1)})}
function t806__startClickBtn(test){var testWrap=$('#rec'+test);var questionFirst=1;var testBtnStart=testWrap.find('.t806__start-btn');testBtnStart.on('click',function(e){var testStart=$(this).parents('.t806__start');testStart.hide();testStart.next().show();t806__showNumber(test,questionFirst);t806_fixcontentheight(test);t806_scrollToTop(testWrap);if(typeof $(".t-records").attr("data-tilda-mode")=="undefined"){if(window.lazy==='y'||$('#allrecords').attr('data-tilda-lazy')==='yes'){t_onFuncLoad('t_lazyload_update',function(){t_lazyload_update()})}}
e.preventDefault()})}
function t806__changeRadio(test,rightansw){var testBlock=$('#rec'+test);var testInput=testBlock.find('.t806__input[type="radio"]');var lastQuestion=testBlock.find('.t806__question').last();lastQuestion.addClass('t806__lastquestion');testInput.change(function(){var rightAnswersCount=testBlock.find('.t806__counter').attr('data-count');var testItem=$(this).parents('#rec'+test+' .t806__question');var testAnswers=$(this).parents('#rec'+test+' .t806__answers');var answerVote=$(this).parents('#rec'+test+' .t806__answers').find('.t806__answer .t-vote__btn-res');var currentRightAnswer=rightansw[testItem.attr('data-question-num')-1];if($(this).attr('type')==='radio'){var checkedRadio=$(this).val();testAnswers.addClass('t806__answers_answered');if(testItem.hasClass('t806__lastquestion')){testAnswers.siblings('.t806__btn-wrapper').find('.t806__btn_result').addClass('t806__btn_show')}else{testAnswers.siblings('.t806__btn-wrapper').find('.t806__btn_next').addClass('t806__btn_show')}
testItem.find('.t806__input').attr('disabled',!0);if(+checkedRadio===+currentRightAnswer){rightAnswersCount++;testBlock.find('.t806__counter').attr('data-count',rightAnswersCount)}
if(+testItem.find('.t806__input:checked').val()!==+currentRightAnswer){testItem.find('.t806__input:checked').parents('.t806__answer').addClass('t806__answer_wrong')}
testItem.find('.t806__input:checked').parent().siblings('.t806__details').show();testItem.find('.t806__input[value="'+currentRightAnswer+'"]').parents('.t806__answer').addClass('t806__answer_correct');answerVote.addClass('t806__answer-vote_show');testItem.find('.t806__input:checked').parents('.t806__answer_correct').addClass('t806__answer_withoutopacity');testItem.find('.t806__input[type="radio"]').parents('.t806__answer_correct').addClass('t806__answer_withoutopacity')}
t806_fixcontentheight(test)})}
function t806__changeTestInput(test){var testBlock=$('#rec'+test);var testInput=testBlock.find('.t806__input[type="checkbox"]');var lastQuestion=testBlock.find('.t806__question').last();var checkedAnswerCheck=[];testBlock.find('.t806__answers').attr('data-test-checked','');lastQuestion.addClass('t806__lastquestion');testInput.change(function(){var testAnswers=$(this).parents('#rec'+test+' .t806__answers');if($(this).attr('type')==='checkbox'){testAnswers.siblings('.t806__btn-wrapper').find('.t806__btn_check').addClass('t806__btn_show')}
if($(this).attr('type')==='checkbox'&&$(this).is(':checked')&&checkedAnswerCheck.indexOf($(this).val())===-1){checkedAnswerCheck.push($(this).val())}
if($(this).attr('type')==='checkbox'&&!$(this).is(":checked")){checkedAnswerCheck.splice(checkedAnswerCheck.indexOf($(this).val()),1)}
testAnswers.attr('data-test-checked',checkedAnswerCheck.join(','));t806_fixcontentheight(test)});return checkedAnswerCheck}
function t806__checkClickBtn(test,rightansw){var rightChecked=!1;var testBlock=$('#rec'+test);var testBtnCheck=testBlock.find('.t806__btn_check');var testInput=testBlock.find('.t806__input');var checkedAnswersTruth=[];testBtnCheck.on('click',function(e){var rightAnswersCount=testBlock.find('.t806__counter').attr('data-count');var testItem=$(this).parents('#rec'+test+' .t806__question');var testAnswers=$(this).parents('#rec'+test+' .t806__question').find('.t806__answers');var answerVote=$(this).parents('.t806__btn-wrapper').siblings('#rec'+test+' .t806__answers').find('.t806__answer .t-vote__btn-res');var checkboxAnswersArr=[];var checkboxAnswers=rightansw[testItem.attr('data-question-num')-1].split(',');var checkedAnswers=testAnswers.attr('data-test-checked').split(',');for(var i=0;i<checkboxAnswers.length;i++){checkboxAnswersArr.push(checkboxAnswers[i])}
testItem.find(testInput).attr('disabled',!0);answerVote.addClass('t806__answer-vote_show');checkedAnswers.forEach(function(item,i){var checkedCheckboxSort=checkedAnswers.sort();var checkboxAnswersArrSort=checkboxAnswersArr.sort();if(+checkedCheckboxSort[i]===+checkboxAnswersArrSort[i]&&checkedCheckboxSort.length===checkboxAnswersArrSort.length){checkedAnswersTruth.push(1)}else{checkedAnswersTruth.push(0)}});var rightChecked=checkedAnswersTruth.every(function(item){return item==1});if(testItem.find(testInput).attr('type')==='checkbox'){checkboxAnswersArr.forEach(function(item){testItem.find('.t806__input[value="'+ +item+'"]').parents('.t806__answer').addClass('t806__answer_correct')});checkedAnswers.forEach(function(item){if(checkboxAnswersArr.indexOf(item)===-1){testItem.find('.t806__input[value="'+ +item+'"]:checked').parents('.t806__answer').addClass('t806__answer_wrong');testItem.find('.t806__input[value="'+ +item+'"]').parent().siblings().show()}})}
testItem.find('.t806__input:checked').parents('.t806__answer_correct').addClass('t806__answer_withoutopacity');if(rightChecked){rightAnswersCount++;testBlock.find('.t806__counter').attr('data-count',rightAnswersCount)}
checkedAnswersTruth=[];$(this).removeClass('t806__btn_show');if(testItem.hasClass('t806__lastquestion')){$(this).parents('.t806__question').find('.t806__btn_result').addClass('t806__btn_show')}else{$(this).parents('.t806__question').find('.t806__btn_next').addClass('t806__btn_show')}
testAnswers.addClass('t806__answers_answered');t806_fixcontentheight(test);if(typeof $(".t-records").attr("data-tilda-mode")=="undefined"){if(window.lazy==='y'||$('#allrecords').attr('data-tilda-lazy')==='yes'){t_onFuncLoad('t_lazyload_update',function(){t_lazyload_update()})}}
testItem.find('.t806__input:checked').parent().siblings('.t806__details').show();t806__changeTestInput(test);e.preventDefault()})}
function t806__nextClickBtn(test){var testBlock=$('#rec'+test);var testBtnNext=testBlock.find('.t806__btn_next');var questionNumber;testBtnNext.on('click',function(e){var parentTop=$(this).parents('#rec'+test+' .t806').offset().top;var testItem=$(this).parents('#rec'+test+' .t806__question');questionNumber=testItem.next().attr('data-question-num');testItem.hide();testItem.next().show();t806__showNumber(test,questionNumber);t806_fixcontentheight(test);t806_scrollToTop(testBlock);if(typeof $(".t-records").attr("data-tilda-mode")=="undefined"){if(window.lazy==='y'||$('#allrecords').attr('data-tilda-lazy')==='yes'){t_onFuncLoad('t_lazyload_update',function(){t_lazyload_update()})}}
e.preventDefault()})}
function t806__resultClickBtn(test){var testBtnResult=$('#rec'+test+' .t806__btn_result');var testBlock=$('#rec'+test);testBtnResult.on('click',function(e){var parentTop=$(this).parents('#rec'+test+' .t806__test').offset().top;var testItem=$(this).parents('#rec'+test+' .t806__question');testItem.hide();t806_scrollToTop(testBlock);t806__showResult(test);t806_fixcontentheight(test);if(typeof $(".t-records").attr("data-tilda-mode")=="undefined"){if(window.lazy==='y'||$('#allrecords').attr('data-tilda-lazy')==='yes'){t_onFuncLoad('t_lazyload_update',function(){t_lazyload_update()})}}
e.preventDefault()})}
function t806__restartClickBtn(test,rightansw){var testBlock=$('#rec'+test);var testContainer=testBlock.find('.t806');var testRestart=testBlock.find('.t806__btn_restart');var testItemAll=testBlock.find('.t806__question');testRestart.on('click',function(e){testBlock.find('.t806__start').show();testBlock.find('.t806__result').hide();testBlock.find('.t806__btn_next').removeClass('t806__btn_show');testBlock.find('.t806__btn_result').removeClass('t806__btn_show');testBlock.find('.t806__btn_check').removeClass('t806__btn_show');testBlock.find('.t806__details').hide();testBlock.find('.t806__answers').removeClass('t806__answers_answered');testBlock.find('.t806__answers').attr('data-test-checked','');testBlock.find('.t806__answer').removeClass('t806__answer_correct');testBlock.find('.t806__answer').removeClass('t806__answer_wrong');testBlock.find('.t806__input').parents('.t806__answer').removeClass('t806__answer_withoutopacity');testBlock.find('.t806__input').prop('checked',!1);testBlock.find('.t806__input').removeAttr('disabled');testBlock.find('.t806__answer .t-vote__btn-res').removeClass('t806__answer-vote_show');$('#rec'+test+' .t806__counter').attr('data-count',0);testBlock.find('.t806__number').text(1+'/'+testItemAll.length);t806_fixcontentheight(test);if(testContainer.hasClass('t806__test-reload')){document.location.reload(!0)}
e.preventDefault()})}
function t806__showResult(test){var testBlock=$('#rec'+test);var testContainer=testBlock.find('.t806');var fullResult=testBlock.find('.t806__result');var startImg=testBlock.find('.t806__start-img img');var fullResultLength=fullResult.length;var allResult;var resultLength=testBlock.find('.t806__result').length;var rightAnswersCount=$('#rec'+test).find('.t806__counter').attr('data-count');var testItemAll=$('#rec'+test+' .t806__question');var resultCount=$('#rec'+test+' .t806__result .t806__result-count');var resultPercent=rightAnswersCount!=0?rightAnswersCount/testItemAll.length*100:0;if(testContainer.hasClass('t806__result-new-calc')){if(Math.floor(resultPercent)!==resultPercent){resultPercent=resultPercent.toFixed(3)}}
resultCount.text(rightAnswersCount+'/'+testItemAll.length);t806__openResultWrapper(testContainer,resultPercent,testBlock,fullResultLength);var resultData=[];fullResult.each(function(i){if($(fullResult[i]).css('display')=='block'){resultData[0]=$(fullResult[i]).find('.t806__result-variant').text()
resultData[1]=$(fullResult[i]).find('.t806__result-count').text();resultData[2]='';var img=$(fullResult[i]).find('.t806__result-wrap img');if(testContainer.hasClass('t806__test-reload')){if(img.length!=0){if(typeof window.lazy!=='undefined'){resultData[2]=img.attr('data-original')||img.attr('src')}else{resultData[2]=img.attr('src')}}
if(img.length==0&&startImg.length!=0){if(typeof window.lazy!=='undefined'){resultData[2]=startImg.attr('data-original')||img.attr('src')}else{resultData[2]=startImg.attr('src')}}}
if(!testContainer.hasClass('t806__test-reload')){if(img.length!=0){resultData[2]=img.attr('src')}
if(img.length==0&&startImg.length!=0){resultData[2]=startImg.attr('src')}}
resultData[3]=$(fullResult[i]).attr('data-quiz-result-number')}});return resultData}
function t806__openResultWrapper(testContainer,resultPercent,testBlock,fullResultLength){if(testContainer.hasClass('t806__result-new-calc')){if(resultPercent<=100*1/fullResultLength){testBlock.find('.t806__result_1').show();return}
for(var i=0;i<fullResultLength;i++){var minResult=100*(i+1)/fullResultLength;var maxResult=100*(i+2)/fullResultLength;minResult=Math.floor(minResult)==minResult?minResult:minResult.toFixed(3);maxResult=Math.floor(maxResult)==maxResult?maxResult:maxResult.toFixed(3);if(resultPercent>=minResult&&resultPercent<=maxResult){testBlock.find('.t806__result_'+(i+2)).show();return}}
if(resultPercent>100*(fullResultLength-1)/fullResultLength){testBlock.find('.t806__result_'+fullResultLength).show();return}}else{if(resultPercent<=100*1/fullResultLength){testBlock.find('.t806__result_1').show()}
for(var i=0;i<fullResultLength;i++){if(resultPercent>100*(i+1)/fullResultLength&&resultPercent<=100*(i+2)/fullResultLength){testBlock.find('.t806__result_'+(i+2)).show()}}
if(resultPercent>100*(fullResultLength-1)/fullResultLength){testBlock.find('.t806__result_'+fullResultLength).show()}}}
function t806__showNumber(test,number){var testItemNumber=$('#rec'+test+' .t806__number');var testItemAll=$('#rec'+test+' .t806__question');testItemNumber.html('<span>'+number+'</span>'+'<span>/</span>'+'<span>'+testItemAll.length+'</span>')}
function t806_fixcontentheight(id){var el=$("#rec"+id);var hcover=el.find(".t-cover").height();var hcontent=el.find("div[data-hook-content]").outerHeight();if(hcontent>300&&hcover<hcontent){var hcontent=hcontent+120;if(hcontent>1000){hcontent+=100}
el.find(".t-cover").height(hcontent);el.find(".t-cover__filter").height(hcontent);el.find(".t-cover__carrier").height(hcontent);el.find(".t-cover__wrapper").height(hcontent);if($isMobile==!1){setTimeout(function(){var divvideo=el.find(".t-cover__carrier");if(divvideo.find('iframe').length>0){setWidthHeightYoutubeVideo(divvideo,hcontent+'px')}},2000)}}}
function t806_changeShareFBUrl(siteLocation,searchUrl){var url=siteLocation.split('?')[0]+'?';var searchParametrs=decodeURIComponent(searchUrl.substring(1));var params=searchParametrs.split('&');params.forEach(function(item){if(item.indexOf('fb_action_ids')==-1&&item.indexOf('fb_action_types')==-1&&item.indexOf('result')==-1){url=url+item+'&'}});url=url.substring(0,url.length-1);return url}
function t806_shareVK(recid,ptitle,purl){var dataForShare=t806__showResult(recid);var text=dataForShare[0];var count=dataForShare[1];var slash=(dataForShare[2]||"").indexOf('/')==0?'':'/';var urlPathname=window.location.pathname.length>1?window.location.pathname:'';var img=(dataForShare[2]||"").indexOf('://')!=-1?dataForShare[2]:window.location.protocol+'//'+window.location.host+urlPathname+slash+dataForShare[2];var resultNumber=dataForShare[3];var idUrl=recid+resultNumber+'vk';var urlValueImg='https://vote.tildacdn.com/vote/2/share/index.php?text='+text;urlValueImg+='&result='+count;if((dataForShare[2]||"").length>0){urlValueImg+='&url='+img}
urlValueImg+='&id='+idUrl;urlValueImg+='&social=vk'+'&name='+ptitle;var value=$.ajax({url:urlValueImg,type:'GET',async:!1,data:{format:'json'},error:function(e){console.log('t806 error: '+e)},complete:function(data){var urlImg=(data.responseJSON.url||'').replace(/\?.*/,'');var shareUrl=window.location.href.indexOf('#')!=-1?purl.split('#')[0]:purl;url='http://vkontakte.ru/share.php?url='+shareUrl+'&title='+ptitle+'&description='+ptitle+'&image='+urlImg+'&noparse=true';t806__openPopup(url)}})}
function t806_shareFB(recid,ptitle,pdescr,purl){var dataForShare=t806__showResult(recid);var text=dataForShare[0];var count=dataForShare[1];var slash=(dataForShare[2]||"").indexOf('/')==0?'':'/';var urlPathname=window.location.pathname.length>1?window.location.pathname:'';var img=(dataForShare[2]||"").indexOf('://')!=-1?dataForShare[2]:window.location.protocol+'//'+window.location.host+urlPathname+slash+dataForShare[2];var resultNumber=dataForShare[3];var idUrl=recid+resultNumber+'fb';var param=count.substring(0,count.indexOf('/'))+count.substring(count.indexOf('/')+1);var urlValueImg='https://vote.tildacdn.com/vote/2/share/index.php?text='+text;urlValueImg+='&result='+count;if((dataForShare[2]||"").length>0){urlValueImg+='&url='+img}
urlValueImg+='&id='+idUrl;urlValueImg+='&social=fb'+'&name='+ptitle;var value=$.ajax({url:urlValueImg,type:'GET',async:!1,data:{format:'json'},error:function(e){console.log('t806 error: '+e)},complete:function(data){var urlImg=data.responseJSON.url;var searchUrl=window.location.search;purl=(searchUrl!==''?t806_changeShareFBUrl(purl,searchUrl):purl)+'?result='+param;FB.ui({method:'share_open_graph',action_type:'og.shares',action_properties:JSON.stringify({object:{'og:url':purl}})})}})}
function t806_shareTwitter(recid,ptitle,purl){var dataForShare=t806__showResult(recid);var testWrap=$('#rec'+recid);var testContainer=testWrap.find('.t806');var text=dataForShare[0];var count=dataForShare[1];var img=dataForShare[2];var resultCount=count.substring(0,count.indexOf('/'));var allCount=count.substring(count.indexOf('/')+1)
var result;if(testContainer.hasClass('t806__ru')){result='Мой результат: '+resultCount+' из '+allCount+'. '+text}
if(testContainer.hasClass('t806__en')){result='My result: '+resultCount+' out of '+allCount+'. '+text}
purl=purl.replace(/&/g,'%26');url='https://twitter.com/share?url='+purl+'&text='+result;url=encodeURI(url);t806__openPopup(url)}
function t806__openPopup(url){window.open(url,'','toolbar=0,status=0,width=626,height=436')}
function t826_init(recid){var el=$('#rec'+recid);t826_startAnimation(recid);if(!window.isMobile){$(window).bind('resize',t_throttle(function(){$("div:not(.t826__animation) > div[data-galaxy-id="+recid+"]").remove();t826_startAnimation(recid)}))}
if(window.isMobile){$(window).on("orientationchange",function(){$("div:not(.t826__animation) > div[data-galaxy-id="+recid+"]").remove();t826_startAnimation(recid)})}
el.find('.t826').bind('displayChanged',function(){$("div:not(.t826__animation) > div[data-galaxy-id="+recid+"]").remove();t826_startAnimation(recid)})}
function t826_startAnimation(recid){var el=$('#rec'+recid);var GalaxyEl=el.find(".t826__galaxy");var wr=el.find(".t826");var recs=wr.attr("data-galaxy-rec-ids");var wholepage=wr.attr("data-galaxy-whole-page");var vertFlip=wr.attr("data-galaxy-vflip");var color=wr.attr("data-element-color");var opacity=wr.attr("data-element-opacity");var options={'color':(!color?"#fff":color),'opacity':(!opacity?1:opacity.replace(/^0?.([0-9])0?$/g,".$1"))};if(options.color.indexOf('#')!==-1){var color=options.color;if(color[1]===color[2]&&color[3]===color[4]&&color[5]===color[6]){options.color="#"+color[1]+color[3]+color[5]}}
if(vertFlip==="yes"){GalaxyEl.addClass("t826__galaxy_flip")}
if($("#allrecords").attr("data-tilda-mode")==="edit"){t826_addAnimation(el.find(".t826__demo"),GalaxyEl,options);return}
if(typeof recs!=="undefined"){recs=recs.split(",");recs.forEach(function(rec,index,array){var curRec=$("#rec"+rec);var curGalaxyEl=GalaxyEl.clone().css("position","absolute");t826_addAnimation(curRec,curGalaxyEl,options)})}else{var nextBlock=el.next(":has(.t-cover)");var prevBlock=el.prev(":has(.t-cover)");var curGalaxyEl=GalaxyEl.clone().css("position","absolute");if(nextBlock.length!==0){t826_addAnimation(nextBlock,curGalaxyEl,options)}else if(prevBlock.length!==0){t826_addAnimation(prevBlock,curGalaxyEl,options)}}
if(wholepage==="yes"){el.find(".t826__animation").css("display","block");t826_addAnimation($("#allrecords"),GalaxyEl.css("position","fixed"),options)}}
function t826_addAnimation(curRec,GalaxyEl,options){curRec.attr("data-animationappear","off").removeClass('r_hidden');var curRecType=curRec.attr("data-record-type");var curRecId=curRec.attr("id");if(curRecType==="396"){curRec.find(".t396__filter").after(GalaxyEl);GalaxyEl.css("z-index","0")}else if(curRecId==="allrecords"){GalaxyEl.css("z-index","-1")}else{var coverWrapper=curRec.find(".t-cover");if(coverWrapper.length>0){coverWrapper.find(".t-cover__filter").after(GalaxyEl);GalaxyEl.css("z-index","0")}else{var wrapper=curRec;if(wrapper.length===0){return!0}
wrapper.append(GalaxyEl);wrapper.css("position","relative");wrapper.children("div").first().css({"position":"relative","z-index":"1"});if(curRecType=='734'||curRecType=='675'||curRecType=='215'){return}
var excludesBlocks=[754,776,778,786,770];if(excludesBlocks.indexOf(parseInt(curRecType,10))!==-1){wrapper.children("div").first().css('z-index','');GalaxyEl.css("z-index","-1")}else{GalaxyEl.css("z-index","0")}}}
t826_runningAnimation(curRec,options)}
function t826_runningAnimation(curRec,options){var starsSetting;if(window.isMobile){starsSetting=[{name:"near",count:25,speed:50},{name:"mid",count:50,speed:100},{name:"far",count:175,speed:150}]}else{starsSetting=[{name:"near",count:100,speed:50},{name:"mid",count:200,speed:100},{name:"far",count:700,speed:150}]}
var curRecId=curRec.attr("id");var maxHeight=curRec.outerHeight();var maxWidth=curRec.outerWidth();if(typeof curRecId==="undefined"){curRecId="demo"}else if(curRecId==="allrecords"){maxHeight=$(window).height();maxWidth=$(window).width()}
var animationName="t826__galaxy-"+curRecId;curRec.find("#"+animationName).remove();var newStyle=document.createElement("style");newStyle.id=animationName;newStyle.innerHTML="@keyframes "+animationName+"{"+"to{"+"transform:translateY("+(-maxHeight)+"px)"+"}"+"}";starsSetting.forEach(function(value,index,array){var x=Math.round(Math.random()*maxHeight);var y=Math.round(Math.random()*maxWidth);var dot="";if(options.color.indexOf('#')!==-1){dot=x+"px "+y+"px"}else{if(options.opacity<1){dot=x+"px "+y+"px rgba("+options.color+","+options.opacity+")"}else{dot=x+"px "+y+"px rgb("+options.color+")"}}
var countDots=Math.round(array[index].count*maxHeight/2000);for(var i=0;i<countDots;i++){var x=Math.round(Math.random()*maxWidth);var y=Math.round(Math.random()*maxHeight);if(options.color.indexOf('#')!==-1){dot+=", "+x+"px "+y+"px";dot+=", "+x+"px "+(y+maxHeight)+"px"}else{if(options.opacity<1){dot+=", "+x+"px "+y+"px rgba("+options.color+","+options.opacity+")";dot+=", "+x+"px "+(y+maxHeight)+"px rgba("+options.color+","+options.opacity+")"}else{dot+=", "+x+"px "+y+"px rgb("+options.color+")";dot+=", "+x+"px "+(y+maxHeight)+"px rgb("+options.color+")"}}}
var animationDuration=Math.round(array[index].speed*maxHeight/2000);className="t826__galaxy-"+array[index].name+"-"+curRecId;newStyle.innerHTML+="."+className+":after, ."+className+"{"+"box-shadow:"+dot+";"+"animation-duration:"+animationDuration+"s;"+"animation-name:"+animationName+";"+(options.color.indexOf('#')!==-1?"color:"+options.color+";":"")+(options.color.indexOf('#')!==-1&&options.opacity<1?"opacity:"+options.opacity:"")+"}"+"."+className+":after{"+"content:' ';"+"position:absolute;"+"top:"+maxHeight+"px"+"}";curRec.find(".t826__galaxy > .t826__galaxy-wrapper > .t826__galaxy-"+array[index].name).addClass(className)});curRec.prepend(newStyle);curRec.find(".t826__galaxy > .t826__galaxy-wrapper").css("animation-name","t826__galaxy-fadeIn")}